/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

import java.awt.Toolkit;
import java.awt.Cursor;

/**
 *
 * @author Poste8
 */
public class FenConnexion extends javax.swing.JFrame {

    /**
     * Creates new form FenConnexion
     */
    public FenConnexion() {
        initComponents();
        complementGUI();
    }
    private void complementGUI() {
        setIconImage(Toolkit.getDefaultToolkit()
            .getImage(getClass()
            .getResource("/images/logoNetBeans.png")));
        setTitle("GSB FACTURATION");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Quitter = new javax.swing.JButton();
        jBtn_Valider = new javax.swing.JButton();
        jPassword_MPD = new javax.swing.JPasswordField();
        jTxt_Nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabe_MDP = new javax.swing.JLabel();
        jLab_Nom = new javax.swing.JLabel();
        jLab_Ecran = new javax.swing.JLabel();
        jLab_MiniFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/valider.png"))); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.setCursor(new Cursor(Cursor.HAND_CURSOR));
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jPassword_MPD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword_MPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_MPDActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword_MPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 30));

        jTxt_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxt_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/switch-on.png"))); // NOI18N
        jLabel1.setText("Paramètres de connexion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabe_MDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabe_MDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/key.png"))); // NOI18N
        jLabe_MDP.setText("Mot de passe");
        getContentPane().add(jLabe_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/utilisateur.png"))); // NOI18N
        jLab_Nom.setText("Nom");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLab_Ecran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLab_Ecran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/ecran.png"))); // NOI18N
        jLab_Ecran.setText("Connexion au programme");
        jLab_Ecran.setToolTipText("");
        getContentPane().add(jLab_Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLab_MiniFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/ban.png"))); // NOI18N
        jLab_MiniFond.setText("jLabel1");
        jLab_MiniFond.setToolTipText("");
        getContentPane().add(jLab_MiniFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_NomActionPerformed

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jPassword_MPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_MPDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_MPDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JLabel jLab_Ecran;
    private javax.swing.JLabel jLab_MiniFond;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLabe_MDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword_MPD;
    private javax.swing.JTextField jTxt_Nom;
    // End of variables declaration//GEN-END:variables
}
