/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogue;

import java.awt.Toolkit;
import java.awt.Cursor;
import controle.connection.ControleConnexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Poste8
 */
public class FenConnexion extends javax.swing.JFrame {

    /**
     * Creates new form FenConnexion
     */
    public FenConnexion() {
        initComponents();
        complementGUI();
    }
    private void complementGUI() {
        setIconImage(Toolkit.getDefaultToolkit()
            .getImage(getClass()
            .getResource("/images/logoNetBeans.png")));
        setTitle("GSB FACTURATION");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Quitter = new javax.swing.JButton();
        jBtn_Valider = new javax.swing.JButton();
        jPassword_MDP = new javax.swing.JPasswordField();
        jTxT_Nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabe_MDP = new javax.swing.JLabel();
        jLab_Nom = new javax.swing.JLabel();
        jLab_Ecran = new javax.swing.JLabel();
        jLab_MiniFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/valider.png"))); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        jBtn_Valider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_ValiderKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jPassword_MDP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword_MDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_MDPActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 30));

        jTxT_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxT_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxT_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTxT_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/switch-on.png"))); // NOI18N
        jLabel1.setText("Paramètres de connexion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabe_MDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabe_MDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/key.png"))); // NOI18N
        jLabe_MDP.setText("Mot de passe");
        getContentPane().add(jLabe_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/utilisateur.png"))); // NOI18N
        jLab_Nom.setText("Nom");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLab_Ecran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLab_Ecran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/ecran.png"))); // NOI18N
        jLab_Ecran.setText("Connexion au programme");
        jLab_Ecran.setToolTipText("");
        getContentPane().add(jLab_Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLab_MiniFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/ban.png"))); // NOI18N
        jLab_MiniFond.setText("jLabel1");
        jLab_MiniFond.setToolTipText("");
        getContentPane().add(jLab_MiniFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxT_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxT_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxT_NomActionPerformed

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jPassword_MDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_MDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_MDPActionPerformed

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        // TODO add your handling code here:
        if(controleConnexion_Appel()){
            try {     
            ControleConnexion.transfertDonnees();            
        } catch (SQLException ex) {
            Logger.getLogger(FenConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
            FenMenuPrincipal laFenetre = new FenMenuPrincipal();
            laFenetre.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_ValiderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_ValiderKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if(controleConnexion_Appel()){
                try {
                    ControleConnexion.transfertDonnees();
                } catch (SQLException ex) {
                    Logger.getLogger(FenConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            FenMenuPrincipal laFenetre = new FenMenuPrincipal();
            laFenetre.setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_jBtn_ValiderKeyPressed

    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JLabel jLab_Ecran;
    private javax.swing.JLabel jLab_MiniFond;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLabe_MDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword_MDP;
    private javax.swing.JTextField jTxT_Nom;
    // End of variables declaration//GEN-END:variables

    
    private boolean controleConnexion_Appel() {
// contrôle de la saisie
    String leNom = jTxT_Nom.getText();
    boolean bControle = false;
    String leMotDePasse = String.valueOf(jPassword_MDP.getPassword());
    if (ControleConnexion.controle(leNom, leMotDePasse)) {
        if (ControleConnexion.isEtatConnexion()) {
        } else {       
        bControle = true;
        JOptionPane.showMessageDialog(null,
            "Impossible de se connecter."
            + " à la base de données ’\n\n’"
            + "Vos nom et mot de passe sont corrects.\n"
            + "Mais les paramètres pour le pilote"
            + " et la base de données "
            + "doivent être vérifiés. ’\n’"
            + "Contactez le responsable informatique.",
            "ALERTE", JOptionPane.ERROR_MESSAGE);
        }
    }
return bControle;
}

}
